### PR TITLE
resurrect crabs

### PR DESCRIPTION
**Pull request by GamingGeek**
crab

### CODE REVIEW

**Comment by deamsy** [comment]
The crabs in PatchManager.java cause confusion when reading logs, so these cannot be added back.

**Comment by GamingGeek** [comment]
the mcgradle version of Hyperium isn't released, the crabs will obviously be removed before release. let them live a little longer

**Comment by deamsy** [comment]
they never died, just moved to different projects

**Comment by GamingGeek** [comment]
the crabs want to move back

**Pull request closed without merging**
